stages:
    - test
    - package
    - deploy

.install_common_tools: &install_common_tools |
    apt-get update
    apt-get install -y ssh

.create_veracode_credentials: &create_veracode_credentials |
    mkdir ~/.veracode
    cat <<EOF> ~/.veracode/credentials
    [DEFAULT]
    VERACODE_API_ID = ${VERACODE_API_ID}
    VERACODE_API_SECRET = ${VERACODE_API_SECRET}
    EOF

.configiure_ssh_keys: &configiure_ssh_keys |
    umask 400
    mkdir -p ~/.ssh
    echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
    ssh-keyscan -H github.com > ~/.ssh/known_hosts
    eval $(ssh-agent -s)
    ssh-add ~/.ssh/id_rsa
    ssh -T github.com


run unit tests:
    stage: test
    tags:
        - test_runner

    script:
        - *install_common_tools
        - *create_veracode_credentials

        - export SSH_PRIVATE_KEY=${GITHUB_SSH_PRIVATE_KEY}
        - *configiure_ssh_keys
