stages:
    - test
    - package
    - deploy

.install_common_tools: &install_common_tools |
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -yqq
    apt-get install -yqq ssh

.create_veracode_credentials: &create_veracode_credentials |
    mkdir ~/.veracode
    cat <<EOF> ~/.veracode/credentials
    [DEFAULT]
    VERACODE_API_ID = ${VERACODE_API_ID}
    VERACODE_API_SECRET = ${VERACODE_API_SECRET}
    EOF

.configiure_ssh_keys: &configiure_ssh_keys |
    export DOMAIN=$(echo ${PROJECT_URL} | cut -d/ -f3)
    echo $DOMAIN
    umask 077
    mkdir -p ~/.ssh
    echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
    ssh-keyscan -H $DOMAIN > ~/.ssh/known_hosts
    eval $(ssh-agent -s)
    ssh-add ~/.ssh/id_rsa
    ssh -T git@$DOMAIN


run unit tests:
    stage: test
    tags:
        - test_runner

    script:
        - *install_common_tools
        - *create_veracode_credentials

        - export SSH_PRIVATE_KEY=${GITHUB_SSH_PRIVATE_KEY}
        - export PROJECT_URL=${CI_PROJECT_URL}
        - export PROJECT_URL="https://github.com/chuck/"
        - *configiure_ssh_keys
