.install_common_tools: &install_common_tools |
    apt-get update -yqq
    apt-get -qy install ssh git > /dev/null

.configiure_git_repo: &configiure_git_repo |
    export GIT_PROJECT_URL=\
    "git@${GIT_HOST}:${GIT_USER_NAME}/${CI_PROJECT_NAME}.git"
    export DOMAIN=$(echo ${GIT_PROJECT_URL} | cut -d\@ -f2 | cut -d\: -f1)
    umask 077
    mkdir -p ~/.ssh
    echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
    ssh-keyscan -H $DOMAIN > ~/.ssh/known_hosts
    eval $(ssh-agent -s)
    ssh-add ~/.ssh/id_rsa

    git config user.name  ${GIT_USER_NAME}
    git config user.email ${GIT_USER_EMAIL}
    git remote rm origin
    git remote add origin ${GIT_PROJECT_URL}

.create_veracode_credentials: &create_veracode_credentials |
    mkdir ~/.veracode
    cat <<EOF> ~/.veracode/credentials
    [DEFAULT]
    VERACODE_API_ID = ${VERACODE_API_ID}
    VERACODE_API_SECRET = ${VERACODE_API_SECRET}
    EOF


variables:
    GIT_STRATEGY: clone

stages:
    - test
    - package
    - publish

package gitlab repo:
    stage: package
    tags:
        - test_runner

    script:
        - *install_common_tools

        - export GIT_USER_NAME="chuck"
        - export GIT_USER_EMAIL="chuck@gitlab.mothership"
        - export GIT_HOST="gitlab.mothership"
        - export SSH_PRIVATE_KEY=${GITLAB_SSH_PRIVATE_KEY}
        - *configiure_git_repo

        - git checkout master
        - export RELEASE=$(git log -1 --pretty='format:%B' | cut -d':' -f1)
        - export VERSION=$(python3 setup.py -q version --increment ${RELEASE})
        - git add .
        - git commit -m "Version v${VERSION} [skip ci]"
        - git push origin master
        - git tag -a v${VERSION} -m "Version ${VERSION}"
        - git push origin v${VERSION}


publish github release:
    stage: publish
    tags:
        - test_runner

    script:
        - *install_common_tools
        - git pull origin master

        - export GIT_USER_NAME="chuckorde"
        - export GIT_USER_EMAIL="chuckorde@gmail.com"
        - export GIT_HOST="github.com"
        - export SSH_PRIVATE_KEY=${GITHUB_SSH_PRIVATE_KEY}
        - *configiure_git_repo

        - git push -u origin master
        - pip3 install requests # needed for github release
        - python3 setup.py -q github --create-release ${GITHUB_API_TOKEN}
 
# run unit tests:
#     stage: test
#     tags:
#         - test_runner
#
#     script:
#         - *install_common_tools
#         - *create_veracode_credentials
#
#         - export GIT_USER_NAME="chuck"
#         - export GIT_USER_EMAIL="chuck@gitlab.mothership"
#         - export GIT_HOST="gitlab.mothership"
#         - export SSH_PRIVATE_KEY=${GITLAB_SSH_PRIVATE_KEY}
#         - *configiure_git_repo
#
#         - git checkout master
#         - *increment_semantic_version
#         - git add .
#         - git commit -m "Version: v${VERSION} [skip ci]"
#         - git push origin master
#
#         - export GIT_USER_NAME="chuckorde"
#         - export GIT_USER_EMAIL="chuckorde@gmail.com"
#         - export GIT_HOST="github.com"
#         - export SSH_PRIVATE_KEY=${GITHUB_SSH_PRIVATE_KEY}
#         - *configiure_git_repo
#         - git push -u origin master
#
