stages:
    - test
    - package
    - deploy

.create_veracode_credentials: &create_veracode_credentials |
    mkdir ~/.veracode
    # echo "[DEFAULT]" > ~/.veracode/credentials
    # echo "VERACODE_API_ID = ${VERACODE_API_ID}" 
    #         >> ~/.veracode/credentials
    # echo "VERACODE_API_SECRET = ${VERACODE_API_SECRET}" 
    #         >> ~/.veracode/credentials
    # - |
    #   echo 
    #     \[DEFAULT\]\
    #     VERACODE_API_ID = ${VERACODE_API_ID}\
    #     VERACODE_API_SECRET = ${VERACODE_API_SECRET}\
    #     >> ~/.veracode/credentials
    # - cat ~/.veracode/credentials
    - cat > test-multi-lines-text <<'EOF'
        line1
        line 2
        'EOF'
    - cat test-multi-lines-text


run unit tests:
    stage: test
    tags:
        - test_runner

    script:
        - export TEST='THIS IS A TEST'
        - *create_veracode_credentials
