stages:
    - test
    - package
    - deploy

.create_veracode_credentials: &create_veracode_credentials |
    echo '>>>>>>>>>>>>>>>>>>'
    echo $TEST


run unit tests:
    stage: test
    tags:
        - test_runner

    script:
        - export TEST='THIS IS A TEST'
        - *create_veracode_credentials
